name: brain_game
description: Math Arena Brain Game
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0

  dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/CalcMindLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/BrainGame.html
